before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

language: node_js

before_install:
 - sudo apt-get install libgmp3-dev
 - "mysql -e 'create database browserid;'"

node_js:
 - 0.8

notifications:
  irc:
    channels:
      - "irc.mozilla.org#identity"
    use_notice: false
    skip_join: false
  email:
    - lloyd@mozilla.com
    - jrgm@mozilla.com

env:
 - WHAT_TESTS=front MYSQL_USER=root
 - WHAT_TESTS=back_mysql MYSQL_USER=root
 - WHAT_TESTS=back
 - WHAT_TESTS=selenium

mysql:
  adapter: mysql2
  username: root
  encoding: utf8
  database: browserid
